name: Scrap Authors

on:
  push:
    branches: [yacine]

jobs:
  Scrap:
    runs-on: ubuntu-latest

    steps:

      - name: Check out source repository
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_ACCESS_TOKEN}}


      - name: install tor proxy
        run: sudo apt install tor

      - name: run tor
        run: |
          ss -nlt


      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

        

      - name: install dependencies 
        run: |
          python3 -m pip install scholarly
          python3 -m pip install pandas
          python3 -m pip install configparser

          

      - name: scrap 
        run: |
          python3 scripts/V1.0.2/main.py


            
      # push the formatting changes to the PR itself
      - name: Commit autopep8 changes
        run: |
          git config --global user.name 'Mehyac Scrapper'
          git config --global user.email 'mehyac_scrapper@users.noreply.github.com'
          git commit -am "Automated scrapping"
          git push